#!/usr/bin/env node

import fs from "node:fs";
import path from "node:path";

const root = process.cwd();
const lessonsDir = path.join(root, "content", "lessons");
const outputFile = path.join(root, "lib", "generatedLessons.ts");

function assert(condition, message) {
  if (!condition) {
    throw new Error(message);
  }
}

function readLessonFiles() {
  assert(fs.existsSync(lessonsDir), `Missing lessons directory: ${lessonsDir}`);

  return fs
    .readdirSync(lessonsDir)
    .filter((name) => name.endsWith(".json"))
    .sort((a, b) => a.localeCompare(b, undefined, { numeric: true }))
    .map((name) => {
      const fullPath = path.join(lessonsDir, name);
      const raw = fs.readFileSync(fullPath, "utf8");
      const parsed = JSON.parse(raw);
      return { name, data: parsed };
    });
}

function validateLesson(lesson, filename) {
  const requiredStringFields = [
    "id",
    "slug",
    "title",
    "description",
    "content",
    "category",
  ];

  for (const field of requiredStringFields) {
    assert(
      typeof lesson[field] === "string" && lesson[field].trim().length > 0,
      `Invalid ${field} in ${filename}`,
    );
  }

  assert(
    typeof lesson.order === "number" && Number.isFinite(lesson.order),
    `Invalid order in ${filename}`,
  );

  assert(
    typeof lesson.challenge === "object" && lesson.challenge !== null,
    `Missing challenge block in ${filename}`,
  );

  const challengeFields = [
    "description",
    "success_message",
    "validation_query",
  ];
  for (const field of challengeFields) {
    assert(
      typeof lesson.challenge[field] === "string" &&
        lesson.challenge[field].trim().length > 0,
      `Invalid challenge.${field} in ${filename}`,
    );
  }

  if (lesson.deepDive !== undefined) {
    assert(
      typeof lesson.deepDive === "string",
      `Invalid deepDive in ${filename}`,
    );
  }
}

function buildLessonObject(lesson) {
  const { deepDive, ...rest } = lesson;
  const mergedContent =
    typeof deepDive === "string" && deepDive.trim().length > 0
      ? `${lesson.content.trimEnd()}\n\n${deepDive.trim()}`
      : lesson.content;

  return {
    ...rest,
    content: mergedContent,
  };
}

function main() {
  const files = readLessonFiles();
  assert(files.length > 0, `No lesson JSON files found in ${lessonsDir}`);

  const lessons = files.map(({ name, data }) => {
    validateLesson(data, name);
    return buildLessonObject(data);
  });

  lessons.sort((a, b) => a.order - b.order);

  const ids = new Set();
  const slugs = new Set();
  for (const lesson of lessons) {
    assert(!ids.has(lesson.id), `Duplicate lesson id: ${lesson.id}`);
    assert(!slugs.has(lesson.slug), `Duplicate lesson slug: ${lesson.slug}`);
    ids.add(lesson.id);
    slugs.add(lesson.slug);
  }

  const source = `// AUTO-GENERATED FILE. DO NOT EDIT DIRECTLY.\n// Generated by scripts/generate-lessons.mjs from content/lessons/*.json\n\nimport type { Lesson } from "@/types/lesson";\n\nexport const lessons: Lesson[] = ${JSON.stringify(lessons, null, 2)};\n`;

  fs.writeFileSync(outputFile, source, "utf8");
  console.log(`Generated ${outputFile} from ${files.length} lesson files.`);
}

try {
  main();
} catch (error) {
  console.error(error instanceof Error ? error.message : String(error));
  process.exit(1);
}

